#!/bin/sh

# The workaround to make build work on Debian 9 is to 'touch' the files used by MySQL.
# Explanation here:
# https://docs.docker.com/storage/storagedriver/overlayfs-driver/
find /var/lib/mysql -type f -exec touch {} \;
mysqld --user=mysql --skip-name-resolve --bind-address=0.0.0.0 --pid-file=/var/run/mysqld/mysqld.pid --open-files-limit=5120
